---
- hosts: "controllers, workers"
  # remote_user: ubuntu
  become: true
  # become_method: sudo
  # become_user: root
  # connection: ssh

  tasks:
    - name: Config modprobe
      blockinfile:
        path: "/etc/modules-load.d/containerd.conf"
        create: true
        block: |
          overlay
          br_netfilter

    - name: Enable modprobe
      command: |
        modprobe overlay
        modprobe br_netfilter

    - name: sysctl params required by setup, params persist across reboots
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        create: true
        block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply sysctl params without reboot
      command: sysctl --system

    - name: Update the apt package index
      command: apt-get update
    
    - name: Set up the Docker Engine repository
      shell: sudo apt-get install -y ca-certificates curl gnupg lsb-release apt-transport-https

    - name: Add Docker's official GPG key directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: 0755

    - name: Add Docker’s official GPG
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set up the Docker repository
      shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker Engine, containerd, and Docker Compose
      shell: |
        VERSION_STRING=5:23.0.1-1~ubuntu.20.04~focal
        apt-get install -y docker-ce=$VERSION_STRING docker-ce-cli=$VERSION_STRING containerd.io docker-buildx-plugin docker-compose-plugin

    - name: Add your user (ubuntu) to the docker group
      command: usermod -aG docker $USER

    - name: Make sure that 'disabled_plugins' is commented out in your config.toml file
      shell: sed -i 's/disabled_plugins/#disabled_plugins/' /etc/containerd/config.toml

    - name: Restart containerd
      command: systemctl restart containerd

    - name: disable swap
      shell: sudo swapoff -a

    - name: Add k8s gpg key
      shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

    - name: Add K8s Source
      blockinfile:
        path: "/etc/apt/sources.list.d/kubernetes.list"
        create: true
        block: |
          deb https://apt.kubernetes.io/ kubernetes-xenial main

    - name: Install Kubernetes
      shell: |
        apt-get update
        apt-get install -y kubelet=1.24.0-00 kubeadm=1.24.0-00 kubectl=1.24.0-00
        apt-mark hold kubelet kubeadm kubectl

    - name: Install bash completion
      shell: sudo apt-get install -y bash-completion

    - name: Enable kubectl bash completion
      blockinfile:
        path: "/home/ubuntu/.bashrc"
        block: source <(kubectl completion bash)
